name: Build DLL versions of gamemesense.sln

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    build:
        runs-on: windows-2019

        steps:
            - name: Checkout repository
              uses: actions/checkout@v2

            - name: Set up C/C++ environment
              uses: microsoft/setup-msbuild@v1.0.2

            - name: Install CMake
              uses: kitware/setup-cmake@v1.4.0

            - name: Configure CMake
              run: cmake -B build

            - name: Build DLL versions
              run: |
                cmake --build build --config Release -v
                cmake --build build --config Stable -v
                cmake --build build --config Developer -v
                cmake --build build --config Beta -v

            - name: Upload DLL artifacts
              uses: actions/upload-artifact@v2
              with:
                name: dll-artifacts
                path: |
                  ./build/Release/*.dll
                  ./build/Stable/*.dll
                  ./build/Developer/*.dll
                  ./build/Beta/*.dll
