name: Build DLL versions of gamemesense.sln

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main
jobs:
    build:
        runs-on: windows-2019

        steps:
            - uses: actions/checkout@v2

            - name: Set up MSVC
              uses: microsoft/setup-msbuild@v1.0.2

            - name: Build DLL versions of gamemesense.sln
              run: |
                msbuild gamemesense.sln /p:Configuration=Release /p:Platform=x86

