name: Build DLL versions of gamemesense.sln

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      
jobs:
  build:
    runs-on: windows-2019

    steps:
      - uses: actions/checkout@v2

      - name: Set up MSVC
        uses: microsoft/setup-msbuild@v1.0.2

      - name:  Config DXSDK_DIR
        run:   echo "DXSDK_DIR=$GITHUB_WORKSPACE/DXSDK-Dep" >> $GITHUB_ENV
        shell: bash

      - name: Cache DirectX SDK
        id:   cache
        uses: actions/cache@v1
        with:
          path: ~/cache
          key:  cache

      - name: Build DLL versions of gamemesense.sln
        run: |
          msbuild gamemesense.sln /p:Configuration=Release /p:Platform=x86

      - name: Upload DLLs
        uses: actions/upload-artifact@v2
        with:
          name: gamemesense
          path: gamemesense/bin/Release/*.dll
