name: Build DLL versions of gamemesense.sln

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      
jobs:
  build:
    runs-on: windows-2019

    steps:
      - uses: actions/checkout@v2

      - name: Set up MSVC
        uses: microsoft/setup-msbuild@v1.0.2

      - name:  Config DXSDK_DIR
        run:   echo "DXSDK_DIR=$HOME/cache/" >> $GITHUB_ENV
        shell: bash

      - name: Cache DirectX SDK
        id:   cache
        uses: actions/cache@v1
        with:
          path: ~/cache
          key:  cache

      - name: Install DirectX SDK
        if:    steps.cache.outputs.cache-hit != 'true'
        run:  |
              curl -L https://download.microsoft.com/download/a/e/7/ae743f1f-632b-4809-87a9-aa1bb3458e31/DXSDK_Jun10.exe -o _DX2010_.exe
              7z x _DX2010_.exe DXSDK/Include -o_DX2010_
              7z x _DX2010_.exe DXSDK/Lib/x86 -o_DX2010_
              mv _DX2010_/DXSDK $HOME/cache
              rm -fR _DX*_ _DX*_.exe
        shell: bash

      - name: Build DLL versions of gamemesense.sln
        run: |
          msbuild gamemesense.sln /p:Configuration=Release /p:Platform=x86
